import type { AgentStep, GenerationParameters, EditSettings, StylePreset } from '../types'

export const defaultParameters: GenerationParameters = {
  cfgScale: 7.5,
  samplingSteps: 50,
  seed: 42,
  topology: 'auto',
  textureResolution: 2048,
  polyBudget: 30000,
  uvMethod: 'auto',
  outputFormat: 'glb',
}

export const defaultEditSettings: EditSettings = {
  material: {
    baseColor: '#8b5cf6',
    metallic: 0.3,
    roughness: 0.6,
    emission: '#000000',
    emissionStrength: 0,
    normalStrength: 1.0,
  },
  rotation: { x: 0, y: 0, z: 0 },
  scale: 1,
  lighting: 'studio',
  background: '#0a0a1a',
}

export const stylePresets: StylePreset[] = [
  {
    id: 'realistic',
    name: '写实风格',
    thumbnail: '🎨',
    description: '高保真写实渲染，适合产品展示',
    tags: ['PBR', '高精度', '产品'],
  },
  {
    id: 'stylized',
    name: '风格化',
    thumbnail: '✨',
    description: '卡通/手绘风格，低面数艺术',
    tags: ['卡通', 'Low-poly', '艺术'],
  },
  {
    id: 'game-ready',
    name: '游戏资产',
    thumbnail: '🎮',
    description: '优化拓扑，适合实时渲染引擎',
    tags: ['LOD', '优化', '实时'],
  },
  {
    id: 'concept',
    name: '概念设计',
    thumbnail: '💡',
    description: '快速概念可视化，侧重形态探索',
    tags: ['概念', '快速', '迭代'],
  },
  {
    id: 'architectural',
    name: '建筑/场景',
    thumbnail: '🏛️',
    description: '建筑和环境资产，模块化结构',
    tags: ['建筑', '场景', '模块'],
  },
  {
    id: 'character',
    name: '角色模型',
    thumbnail: '🧑‍🎨',
    description: '人物/生物角色，带骨骼绑定准备',
    tags: ['角色', '骨骼', '动画'],
  },
]

export function createMockAgentSteps(): AgentStep[] {
  return [
    {
      id: 'step-1',
      name: '意图解析',
      type: 'intent-parser',
      status: 'pending',
      progress: 0,
      inputs: { prompt: '' },
      outputs: {},
      position: { x: 100, y: 200 },
      connections: ['step-2'],
    },
    {
      id: 'step-2',
      name: '概念生成',
      type: 'concept-generator',
      status: 'pending',
      progress: 0,
      inputs: {},
      outputs: {},
      position: { x: 300, y: 150 },
      connections: ['step-3'],
    },
    {
      id: 'step-3',
      name: '结构生成',
      type: 'structure-generator',
      status: 'pending',
      progress: 0,
      inputs: {},
      outputs: {},
      position: { x: 500, y: 200 },
      connections: ['step-4', 'step-5'],
    },
    {
      id: 'step-4',
      name: '拓扑优化',
      type: 'topology-optimizer',
      status: 'pending',
      progress: 0,
      inputs: {},
      outputs: {},
      position: { x: 700, y: 120 },
      connections: ['step-6'],
    },
    {
      id: 'step-5',
      name: 'UV展开',
      type: 'uv-unwrapper',
      status: 'pending',
      progress: 0,
      inputs: {},
      outputs: {},
      position: { x: 700, y: 280 },
      connections: ['step-6'],
    },
    {
      id: 'step-6',
      name: '细节精修',
      type: 'detail-refiner',
      status: 'pending',
      progress: 0,
      inputs: {},
      outputs: {},
      position: { x: 900, y: 200 },
      connections: ['step-7'],
    },
    {
      id: 'step-7',
      name: '材质生成',
      type: 'texture-generator',
      status: 'pending',
      progress: 0,
      inputs: {},
      outputs: {},
      position: { x: 1100, y: 200 },
      connections: ['step-8'],
    },
    {
      id: 'step-8',
      name: '质量检查',
      type: 'quality-checker',
      status: 'pending',
      progress: 0,
      inputs: {},
      outputs: {},
      position: { x: 1300, y: 200 },
      connections: ['step-9'],
    },
    {
      id: 'step-9',
      name: '格式转换',
      type: 'format-converter',
      status: 'pending',
      progress: 0,
      inputs: {},
      outputs: {},
      position: { x: 1500, y: 200 },
      connections: [],
    },
  ]
}

export const agentTypeLabels: Record<string, { label: string; color: string }> = {
  'intent-parser': { label: '意图解析', color: '#4fc3f7' },
  'concept-generator': { label: '概念生成', color: '#b388ff' },
  'structure-generator': { label: '结构生成', color: '#69f0ae' },
  'detail-refiner': { label: '细节精修', color: '#f48fb1' },
  'topology-optimizer': { label: '拓扑优化', color: '#ffb74d' },
  'uv-unwrapper': { label: 'UV展开', color: '#4dd0e1' },
  'texture-generator': { label: '材质生成', color: '#aed581' },
  'quality-checker': { label: '质量检查', color: '#fff176' },
  'format-converter': { label: '格式转换', color: '#90a4ae' },
}
